### ISSUE TITLE
chromosome arm positions hg19

### ISSUE THREAD

**Issue by ccruizm** [diazlab/CONICS#11]
Good day!

I am really excited to use this interesting tool for my scRNA data. I would like to know where I could find or how I can make the file that contains the chromosome arm position for the genome version Hg19. 

Thanks in advance!

**Comment by WRui** [comment]
you can download cytoBand  or get from CaSpER package.
Chrom   Start   End     Length
1p      1       0       1.25e+08        125000000
1q      1       1.25e+08        249250621       124250621
2p      2       0       93300000        93300000
2q      2       93300000        243199373       149899373
3p      3       0       9.1e+07 91000000
3q      3       9.1e+07 198022430       107022430
4p      4       0       50400000        50400000
4q      4       50400000        191154276       140754276
5p      5       0       48400000        48400000
5q      5       48400000        180915260       132515260
6p      6       0       6.1e+07 61000000
6q      6       6.1e+07 171115067       110115067
7p      7       0       59900000        59900000
7q      7       59900000        159138663       99238663
8p      8       0       45600000        45600000
8q      8       45600000        146364022       100764022
9p      9       0       4.9e+07 49000000
9q      9       4.9e+07 141213431       92213431
10p     10      0       40200000        40200000
10q     10      40200000        135534747       95334747
11p     11      0       53700000        53700000
11q     11      53700000        135006516       81306516
12p     12      0       35800000        35800000
12q     12      35800000        133851895       98051895
13p     13      0       17900000        17900000
13q     13      17900000        115169878       97269878
14p     14      0       17600000        17600000
14q     14      17600000        107349540       89749540
15p     15      0       1.9e+07 19000000
15q     15      1.9e+07 102531392       83531392
16p     16      0       36600000        36600000
16q     16      36600000        90354753        53754753
17p     17      0       2.4e+07 24000000
17q     17      2.4e+07 81195210        57195210
18p     18      0       17200000        17200000
18q     18      17200000        78077248        60877248
19p     19      0       26500000        26500000
19q     19      26500000        59128983        32628983
20p     20      0       27500000        27500000
20q     20      27500000        63025520        35525520
21p     21      0       13200000        13200000
21q     21      13200000        48129895        34929895
22p     22      0       14700000        14700000
22q     22      14700000        51304566        36604566
Xp      X       0       60600000        60600000
Xq      X       60600000        155270560       94670560
Yp      Y       0       12500000        12500000
Yq      Y       12500000        59373566        46873566

**Comment by WRui** [comment]
> Good day!
> 
> I am really excited to use this interesting tool for my scRNA data. I would like to know where I could find or how I can make the file that contains the chromosome arm position for the genome version Hg19.
> 
> Thanks in advance!
you can download cytoBand or get from CaSpER package.
Chrom Start End Length
1p 1 0 1.25e+08 125000000
1q 1 1.25e+08 249250621 124250621
2p 2 0 93300000 93300000
2q 2 93300000 243199373 149899373
3p 3 0 9.1e+07 91000000
3q 3 9.1e+07 198022430 107022430
4p 4 0 50400000 50400000
4q 4 50400000 191154276 140754276
5p 5 0 48400000 48400000
5q 5 48400000 180915260 132515260
6p 6 0 6.1e+07 61000000
6q 6 6.1e+07 171115067 110115067
7p 7 0 59900000 59900000
7q 7 59900000 159138663 99238663
8p 8 0 45600000 45600000
8q 8 45600000 146364022 100764022
9p 9 0 4.9e+07 49000000
9q 9 4.9e+07 141213431 92213431
10p 10 0 40200000 40200000
10q 10 40200000 135534747 95334747
11p 11 0 53700000 53700000
11q 11 53700000 135006516 81306516
12p 12 0 35800000 35800000
12q 12 35800000 133851895 98051895
13p 13 0 17900000 17900000
13q 13 17900000 115169878 97269878
14p 14 0 17600000 17600000
14q 14 17600000 107349540 89749540
15p 15 0 1.9e+07 19000000
15q 15 1.9e+07 102531392 83531392
16p 16 0 36600000 36600000
16q 16 36600000 90354753 53754753
17p 17 0 2.4e+07 24000000
17q 17 2.4e+07 81195210 57195210
18p 18 0 17200000 17200000
18q 18 17200000 78077248 60877248
19p 19 0 26500000 26500000
19q 19 26500000 59128983 32628983
20p 20 0 27500000 27500000
20q 20 27500000 63025520 35525520
21p 21 0 13200000 13200000
21q 21 13200000 48129895 34929895
22p 22 0 14700000 14700000
22q 22 14700000 51304566 36604566
Xp X 0 60600000 60600000
Xq X 60600000 155270560 94670560
Yp Y 0 12500000 12500000
Yq Y 12500000 59373566 46873566
