### ISSUE TITLE
fail to install CONISmat

### ISSUE THREAD

**Issue by RitataLU** [diazlab/CONICS#14]
Hi 
When I run this step "devtools::install_github("diazlab/CONICS/CONICSmat", dep = FALSE)"
I got the following error message

ERROR: dependencies ‘beanplot’, ‘mixtools’, ‘pheatmap’, ‘squash’, ‘scran’ are not available for package ‘CONICSmat’
* removing ‘/diskmnt/Projects/Users/ritalu/miniconda3/lib/R/library/CONICSmat’
Error: Failed to install 'CONICSmat' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmpuHb2D4/file4515252505c5/CONICSmat_0.0.0.1.tar.gz’ had non-zero exit status

**Comment by soerenmueller** [comment]
Hi, 

please run:

install.packages("beanplot")
install.packages("mixtools")
install.packages("pheatmap")
install.packages("squash")

if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("scran")

prior to installing CONCISmat.
