### ISSUE TITLE
getGenePositions() in CONICSmat can not deal with gene names in ENSEMBL format 

### ISSUE THREAD

**Issue by biobug16** [diazlab/CONICS#15]
Hi [soerenmueller](https://github.com/soerenmueller),
I am trying to use 10X data where my filtered matrix has gene names in ENSEMBL format. Going through the CONICSmat pipeline I found getGenePositions() can only accepts the vector of genes in HUGO format. Can you please guide how should I troubleshoot this issue.
Thanks

**Comment by soerenmueller** [comment]
Hi, 

here is some code that allows to convert ensembl to HUGO with the biomart package: 

https://bioinformatics.stackexchange.com/questions/2384/ensembl-id-to-genesymbol-with-biomart

Hope this is helpful.
