### ISSUE TITLE
How to process the natural log values from Seurat into log2(CPM/10+1)

### ISSUE THREAD

**Issue by biobug16** [diazlab/CONICS#16]
Hi All and [soerenmueller](https://github.com/soerenmueller)
I want to use the read count matrix generated by Seurat which which is in natural log scale but don't know how to convert these to log2(CPM/10+1) for the downstream analysis by CONICSmat. If anybody who has already done this before and can share his/her experience.

Any help will be highly appreciated.
Thanks

**Comment by soerenmueller** [comment]
Hi, 

the easiest way to get from Seurat to a log2CPM matrix is as follows: 

mat=seu@assays$RNA@counts
log2mat=CONICSmat::normMat(mat)

This assumes your Seurat object (seu) is processed with Seurat V3. 
Hope this helps.

**Comment by biobug16** [comment]
Hi [soerenmueller](https://github.com/soerenmueller)
Thank you for your kind reply but I got another error:
`Error in t.default(expmat) : argument is not a matrix`
Can you please give it a look. Thanks

**Comment by biobug16** [comment]
Oh ok I guess it was just the `mat<-as.matrix(mat)` which was missing. 
Thanks again for this wonderful tool and your help.
