### ISSUE TITLE
Heatmap of the posterior probabilities highlights cells in red (down-regulation of 1p/19q) and not in blue (up-regulation)

### ISSUE THREAD

**Issue by biobug16** [diazlab/CONICS#17]
Hi [soerenmueller](https://github.com/soerenmueller)
I am using in-house data for idh-mut gliomas, there I don't know why my heatmap for posterior probabilities highlights cells in blue indicating they have down-regulation or deletion of 1p/19q but not as in your case where you got highlighted other set of cells that had higher expression of 1p/19q to later name them as non-malignant. 
I followed the same commands as in the tutorial.
Has anyone also faced this issue before? Or I am doing something wrong?
Any help will be highly appropriated.

**Comment by soerenmueller** [comment]
Hi, 

"I don't know why my heatmap for posterior probabilities highlights cells in red indicating they have down-regulation or deletion of 1p/19q "

In the heatmap cells in red have no downregulation/deletion of 1p/19q. So if you see that in your plot everything should go as proposed? Red means high levels of expression from that chromosome, blue means low levels.

**Comment by soerenmueller** [comment]
"Now, we can visualize a heatmap of the posterior probabilities of cells for component2 of each region. Here, component2 is defined as the component with the larger mean. Therefore cells with a higher expression at that locus will appear in red, cells with a lower expression in blue. Posterior probabilities are given as a row-wise z-score."
