### ISSUE TITLE
error when connecting to BioMart

### ISSUE THREAD

**Issue by snoopy-448** [diazlab/CONICS#2]
HI
I got an error when I tried to run CONICs using the example data:
> gene_pos=getGenePositions(rownames(suva_expr))
Request to BioMart web service failed.
The BioMart web service you're accessing may be down.
Check the following URL and see if this website is available:
http://http://dec2016.archive.ensembl.org:80/biomart/martservice?type=registry&requestid=biomaRt
Error in if (!grepl(x = registry, pattern = "^\n*<MartRegistry>")) { : 
  argument is of length zero
It seems like something goes wrong when I connect to BioMart. Do you have any advice on solving this problem?
Many thanks!

**Comment by diazlab** [comment]
Hi Snoopy,
1. great name
2. did you try clicking the link to see if biomart was in fact down?

Sent from my Verizon 4G LTE Droid
On May 18, 2018 7:34 PM, snoopy-448 <notifications@github.com> wrote:

HI
I got an error when I tried to run CONICs using the example data:

gene_pos=getGenePositions(rownames(suva_expr))
Request to BioMart web service failed.
The BioMart web service you're accessing may be down.
Check the following URL and see if this website is available:
http://http://dec2016.archive.ensembl.org:80/biomart/martservice?type=registry&requestid=biomaRt
Error in if (!grepl(x = registry, pattern = "^\n*")) { :
argument is of length zero
It seems like something goes wrong when I connect to BioMart. Do you have any advice on solving this problem?
Many thanks!

**Comment by snoopy-448** [comment]
Hi, the connection to biomart is still failed for me. I'd appreciate if you could tell me the output format of getGenePositions so I can produce this table by myself. Such as, if I run 
gene_pos = getGenePositions(c('gene1', 'gene2'))
what would be in the gene_pos then?
Thank you !

**Comment by soerenmueller** [comment]
Hi snoopy - Thanks for using CONICS :) 
I just checked the getGenePosistions function and it works fine on windows and Unix, R 3.4.2. What version of R are you using? I remember a while ago biomart changed something in the underlying function, so if you have an outdated biomart package this might be the reason. 

Either way, here is an output of the getGenePosistions function:

`head(gene_pos)
    ensembl_gene_id hgnc_symbol chromosome_name start_position end_position
33  ENSG00000276072        AATF               0       36950708     37058704
62  ENSG00000278183       ABCC1               0       16034690     16228109
73  ENSG00000275331       ABCC6               0       16233991     16308660
85  ENSG00000225989       ABCF1               0       30563598     30589402
109 ENSG00000230475     ABHD16A               0       31677699     31694178
132 ENSG00000281879         ABO               0      133255323    133275362`

**Comment by snoopy-448** [comment]
Thanks a lot!
