### ISSUE TITLE
How to check amplification of a specific gene using CONICSmat?

### ISSUE THREAD

**Issue by biobug16** [diazlab/CONICS#26]
Hi @soerenmueller  I just want to check amplification of EGFR in my scRNA Seq data using CONICSmat. Is there a way to check this specifically this locus instead of just checking for whole chr7p arm?

Looking for your advice. Thanks.

**Comment by diazlab** [comment]
The correlation between DNA copy number and average expression level increases with scale. This approach is generally reliable for regions in the megabase scale, but you will not be able to tell the DNA copy number for just 1 gene from RNA sequencing.

**Comment by biobug16** [comment]
Thank you for the clarification.
