### ISSUE TITLE
Confusion about the calcNormFactors

### ISSUE THREAD

**Issue by snoopy-448** [diazlab/CONICS#3]
So sorry to bother you again.
There is no issue about the software. I am just confused about some description in the guide of CONICSmat. There is a step called calcNormFactors, in which you calculate the mean expression level of each cell and use it as the normalized factor. In the guidance you say that "the more genes expressed in one cell, the less reads are "available" per gene". I can understand this sentence, and think it is reasonable. But what confused me is, could this method (colMeans(suva_expr)) really achieve this goal? 
If there are two cells: C1 and C2. In C1, 100 genes are expressed, each with a expression level of 10; and in C2, 10 genes are expressed, each with a expression level of 100. So, the average expression level (colMeans) of the two cell are the same; they have the same normalized factor but one with 100 genes expressed and one with only 10.
This is what I am confused about. By the way, I also want to ask, which subsequent step needs this normfactor? I am just a beginner of single RNA seq, when I deal with the bulk RNA-seq data before. like do some differential expression analysis. I remember only the CPM/RPKM is enough, as it consider the different reads number between each sample. I don't remember there is a step for calculating this factor. (Maybe those software hide this step in their function and I didn't find it).
Please forgive me for asking such lowly question.
Thanks!

**Comment by snoopy-448** [comment]
Apologize for late reply! Github did not send me an email... Thanks a lot!

**Comment by snoopy-448** [comment]
I have another question, have you tried conics at dropseq data? Cause the genes detected per cell are much less than smartseq, I wonder if it is reasonable to infer CNV from dropseq data...
By the way, if I have multiple samples and I want to plot them in one heatmap using plotChromosomeHeatmap, and want to label each patient with different color left to the heatmap. Could you tell me how to do this?

**Comment by diazlab** [comment]
Yes, we've tried it on 10X data: https://doi.org/10.1186/s13059-017-1362-4 
It works pretty well. It works best for larger CNVs. 

I'll have to think about your labels question...

**Comment by soerenmueller** [comment]
We've also used it in a second paper that's currently available as a pre-print

https://www.biorxiv.org/content/early/2018/04/12/272328

![preprint_clones](https://user-images.githubusercontent.com/13483868/41067816-ce89e41a-699b-11e8-93df-cb66befef21d.jpg)
 
This is 10X data from a single case in which we identify multiple clones using CONICSmat. As already mentioned it works better the larger the CNVs. 

As for plotting the patient ID next to the heatmap: There is currently no function for that, but I assume your matrix is ordered by patients? If so, you can simply draw a horizontal line for cells of each patient. 

For example (assuming the first 1234 cells of your matrix are from patient1): 

abline(h=1234,lty=16,lwd=0.8)

Hope this helps!

**Comment by snoopy-448** [comment]
Thank you very much, indeed my matrix is not ordered. I want to label the patient after clustering and see if cells from one patient cluster together.

**Comment by soerenmueller** [comment]
Makes sense! I will try to integrate that functionality into the package. Which function are you using to plot the results where you want the bar for each patient integrated?

**Comment by snoopy-448** [comment]
By the way, is the data in https://www.biorxiv.org/content/early/2018/04/12/272328 available now? Only the expression matrix will be enough. Thanks!
