### ISSUE TITLE
Error in tutorial

### ISSUE THREAD

**Issue by romagnolid** [diazlab/CONICS#8]
https://github.com/diazlab/CONICS/wiki/Tutorial---CONICSmat;---Dataset:-SmartSeq2-scRNA-seq-of-Oligodendroglioma

    > vg <- detectVarGenes(suva_expr, 500)
    Error in .local(x, ...) : unused argument (span = 0.2)

**Comment by soerenmueller** [comment]
Hey romagnolid, 
could you let me know what version of the scran package you have installed? This seems to be a version issue.

"var.fit = scran::trendVar(mat, span=0.2)"

**Comment by romagnolid** [comment]
Version 1.10.2

Yes, I have the same feeling but after a quick glance at the `scran` package I couldn't spot anything related to the `trendVar` function. I'm probably missing something.

**Comment by pbrazda** [comment]
Hi, 

super-exciting package!
I was eager to test it :) , but I think this problem is somewhat similar to the previous ones:

`vg=detectVarGenes(suva_expr,500)`
Error: object ‘int_colData’ is not exported by 'namespace:SingleCellExperiment'

(scran 1.10.2)

Any tips?
Thanks!

**Comment by pbrazda** [comment]
W

> Hi,
> 
> super-exciting package!
> I was eager to test it :) , but I think this problem is somewhat similar to the previous ones:
> 
> `vg=detectVarGenes(suva_expr,500)`
> Error: object ‘int_colData’ is not exported by 'namespace:SingleCellExperiment'
> 
> (scran 1.10.2)
> 
> Any tips?
> Thanks!


Now, with R version 3.5.2, scran 1.10.2, to
`vg=detectVarGenes(suva_expr,500)`

I also get
`Error in .local(x, ...) : unused argument (span = 0.2)`

**Comment by soerenmueller** [comment]
Hi all, 

thanks for using CONICS :) 

It seems in the most recent version of scran the span argument has been removed. I updated the package accordingly. Please install CONICSmat again using

devtools::install_github("diazlab/CONICS/CONICSmat", dep = FALSE)

and restart your R session. After, the error should be fixed. 

Cheers, 
Soren
