### ISSUE TITLE
Error in string.to.colors() in Tutorial

### ISSUE THREAD

**Issue by erin-d** [diazlab/CONICS#9]
In the tutorial for Tutorial CONICSmat: Inference of clones in GBM single cell data from Darmanis et al, the following command produces the error below.

> pcol=string.to.colors(patients)[c(normal,tumor)]

Error in string.to.colors(patients) : could not find function "string.to.colors"

I looked it up and it seems to be a function from the fifer package, fails to install, because it is not avaliable for R version 3.6.0

Any ideas for how to resolve this issue or is there a different command to run instead that doesn't require this package?

**Comment by soerenmueller** [comment]
Hey, 

thanks for noticing! I fixed the issue by adding the method to the package. Should work now if you re-install CONICSmat

Cheers, 
Soren

**Comment by erin-d** [comment]
Hi,
I removed the package, restarted R, and reinstalled it, and am still having the same issue.
Thanks,
Erin

**Comment by faculty** [comment]
You can refer to https://github.com/cran/fifer for installing fifer.
